version: '3'

services:
  jekyll:
    image: younglook/jekyll-arm64
    # Docker doesn't work with inotify, use --force_polling:
    # https://github.com/jekyll/jekyll-watch/issues/17
    command: jekyll serve --force_polling
    ports:
      - 4000:4000
      - 35729:35729
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
